spring.application.name=todoList
# C?u hình k?t n?i t?i H2
spring.datasource.url=jdbc:h2:mem:todolistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Cho phép Hibernate t? ??ng t?o b?ng d?a trên class
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Kích ho?t giao di?n qu?n lý H2 trên trình duy?t
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console